import { buildGameSummary, getEndingMeter } from "@/src/domain/summary";
import { buildActiveState, buildFlag, buildMeters } from "./fixtures";

function decision(turn, deltas) {
  return {
    turn,
    cardSlug: `card_${turn}`,
    speaker: { id: "helena-vasque", name: "Helena Vasque" },
    choiceLabel: `Escolha ${turn}`,
    deltas: { people: 0, market: 0, congress: 0, institutions: 0, ...deltas },
    metersAfter: buildMeters(),
  };
}

describe("getEndingMeter", () => {
  it("returns the pillar of a collapse ending", () => {
    expect(getEndingMeter("market_dominant")).toBe("market");
    expect(getEndingMeter("institutions_broken")).toBe("institutions");
  });

  it("returns null for the completed mandate", () => {
    expect(getEndingMeter("mandate_completed")).toBeNull();
  });
});

describe("buildGameSummary", () => {
  const decisions = [
    decision(1, { people: 2, market: -2 }),
    decision(2, { people: 7, market: -4, congress: -2 }),
    decision(3, { people: -6, market: 4, congress: 3 }),
    decision(4, { institutions: -1 }),
  ];
  const state = buildActiveState({
    status: "ended",
    turn: 4,
    endingCode: "people_abandoned",
    simultaneousEndingCodes: ["market_collapsed"],
    meters: buildMeters({ people: 0, market: 0 }),
    flags: {
      reform: buildFlag({ legacy: true, label: "Reforma aprovada" }),
      strike: buildFlag({ label: "Greve" }),
    },
  });

  const summary = buildGameSummary({ state, decisions });

  it("reports the ending, its main cause and simultaneous crises", () => {
    expect(summary).toMatchObject({
      endingCode: "people_abandoned",
      primaryMeter: "people",
      simultaneousEndingCodes: ["market_collapsed"],
      mandateCompleted: false,
    });
  });

  it("reports duration in months and years, final pillars and decision count", () => {
    expect(summary.duration).toEqual({ months: 4, years: 0, remainingMonths: 4 });
    expect(summary.finalMeters).toEqual(state.meters);
    expect(summary.decisionsCount).toBe(4);
  });

  it("lists the three decisions with the largest total impact", () => {
    expect(summary.topDecisions.map((entry) => [entry.turn, entry.impact])).toEqual([
      [2, 13],
      [3, 13],
      [1, 4],
    ]);
  });

  it("lists only the legacy flags generated by the government", () => {
    expect(summary.legacyFlags).toEqual([{ key: "reform", label: "Reforma aprovada" }]);
  });

  it("includes the score and the epithet", () => {
    expect(summary.score).toMatchObject({ survivalScore: 400, completionBonus: 0, score: 2400 });
    expect(summary.epithetCode).toBe("brief_government");
  });
});
