// The 30 MVP cards from GDD v1.0 §18. Effects follow Povo / Mercado / Congresso / Instituições.
// Result texts marked in docs/game-rules.md as provisional were written where the GDD has none.
// Each choice carries its own authored consequence: a newspaper `headline` and the speaker's `reaction`.
const fx = (people, market, congress, institutions) => ({ people, market, congress, institutions });

const CRITICAL = (meter) => [
  { meter, min: 1, max: 18 },
  { meter, min: 82, max: 99 },
];

export const cardDefinitions = [
  // §18.1 Common cards
  {
    slug: "emergency_budget",
    type: "common",
    speaker: "caio-ferraz",
    category: "budget",
    text: "A arrecadação caiu. A Fazenda propõe congelar gastos, enquanto governadores exigem a manutenção dos repasses.",
    leftChoice: {
      label: "Congelar gastos",
      effects: fx(-5, 7, -3, 2),
      resultText: "O mercado respira; hospitais regionais anunciam cortes.",
      headline: "Fazenda congela gastos federais e hospitais regionais perdem repasses previstos",
      reaction:
        "Não é popular, Presidente, mas é o que mantém o Tesouro de pé. Os números agradecem antes das pessoas.",
    },
    rightChoice: {
      label: "Manter repasses",
      effects: fx(5, -6, 4, -1),
      resultText: "Governadores celebram, e a dívida ocupa as manchetes.",
      headline: "Governo mantém repasses aos estados apesar da queda na arrecadação federal",
      reaction:
        "Os governadores saem satisfeitos. Eu saio com uma dívida maior e a obrigação de explicá-la aos credores.",
    },
    weight: 10,
    cooldownTurns: 10,
    tags: ["budget", "federalism"],
  },
  {
    slug: "teachers_strike",
    type: "common",
    speaker: "mara-vilar",
    category: "education",
    text: "Professores ameaçam parar as escolas. O reajuste encerra a crise, mas rompe o limite orçamentário.",
    leftChoice: {
      label: "Conceder reajuste",
      effects: fx(7, -4, -2, 0),
      setFlags: [{ key: "teachers_raise" }],
      resultText: "As aulas retornam, mas a equipe econômica exige compensações.",
      headline: "Professores recebem reajuste e aulas são retomadas em todas as redes públicas",
      reaction:
        "As escolas voltam a abrir, e isso vale cada centavo. Agora preciso defender o acordo diante da Fazenda.",
    },
    rightChoice: {
      label: "Manter orçamento",
      effects: fx(-6, 4, 2, 0),
      setFlags: [{ key: "teachers_strike_active", expiresAfterTurns: 8 }],
      schedule: [{ cardSlug: "strike_escalation", delayTurns: 3 }],
      resultText: "Os sindicatos marcam o início da paralisação.",
      headline: "Governo recusa reajuste e sindicatos de professores aprovam greve nacional",
      reaction:
        "Eu avisei que eles não recuariam. Cada dia sem aula vai pesar mais do que o reajuste que negamos.",
    },
    weight: 9,
    cooldownTurns: 14,
    tags: ["education", "labor"],
  },
  {
    slug: "strategic_port_concession",
    type: "common",
    speaker: "tomas-gade",
    category: "infrastructure",
    text: "Um consórcio oferece modernizar o maior porto do país em troca de uma concessão de trinta anos.",
    leftChoice: {
      label: "Assinar concessão",
      effects: fx(-3, 8, 2, -4),
      setFlags: [{ key: "strategic_port_concession" }],
      resultText: "O consórcio assume o porto, e os estivadores prometem vigiar cada cláusula.",
      headline: "Consórcio privado assume o maior porto do país em concessão de trinta anos",
      reaction:
        "Uma decisão à altura de um país que quer competir. A Federação acompanhará de perto cada etapa das obras.",
    },
    rightChoice: {
      label: "Manter controle estatal",
      effects: fx(3, -6, -1, 4),
      resultText: "O porto segue estatal, e investidores anunciam projetos nos países vizinhos.",
      headline: "Porto permanece sob controle estatal e consórcio retira proposta de modernização",
      reaction:
        "Respeito a decisão, Presidente, mas o capital não espera. Os investidores já estudam os portos vizinhos.",
    },
    weight: 8,
    cooldownTurns: 18,
    uniquePerGame: true,
    tags: ["infrastructure", "economy"],
  },
  {
    slug: "hospital_queues",
    type: "common",
    speaker: "icaro-nunes",
    category: "health",
    text: "As filas dobraram. Podemos contratar uma rede privada ou abrir crédito extraordinário para hospitais públicos.",
    leftChoice: {
      label: "Contratar a rede",
      effects: fx(-2, 5, 3, -3),
      resultText: "As filas diminuem, e os auditores questionam os valores do convênio.",
      headline: "Ministério da Saúde contrata rede privada para reduzir filas de atendimento",
      reaction:
        "As filas precisam cair esta semana, não no próximo orçamento. Vou exigir relatórios de cada leito contratado.",
    },
    rightChoice: {
      label: "Abrir crédito público",
      effects: fx(6, -5, -2, 2),
      resultText: "Hospitais públicos reabrem leitos, e a Fazenda revisa as metas do ano.",
      headline: "Crédito extraordinário reabre leitos em hospitais públicos de todo o país",
      reaction:
        "É o caminho certo para o sistema, mas leito sem equipe não salva ninguém. Preciso de contratações já.",
    },
    weight: 10,
    cooldownTurns: 10,
    tags: ["health", "budget"],
  },
  {
    slug: "coalition_amendment",
    type: "common",
    speaker: "raul-mendonca",
    category: "congress",
    text: "A coalizão garante aprovar sua agenda se puder indicar a direção das agências reguladoras.",
    leftChoice: {
      label: "Aceitar indicações",
      effects: fx(-2, 2, 8, -6),
      setFlags: [{ key: "agencies_shared" }],
      resultText: "A agenda avança no Congresso, e as agências passam a responder à coalizão.",
      headline: "Governo cede direção das agências reguladoras à coalizão em troca de votos",
      reaction:
        "Uma parceria madura, Presidente. O Congresso sabe reconhecer quem aceita dividir responsabilidades.",
    },
    rightChoice: {
      label: "Preservar autonomia",
      effects: fx(1, -1, -7, 6),
      resultText: "As agências mantêm a autonomia, e a coalizão engaveta seus projetos.",
      headline: "Palácio veta indicações políticas nas agências e coalizão congela votações",
      reaction:
        "Admiro a firmeza, de verdade. Só não espere que meus colegas votem com o mesmo entusiasmo.",
    },
    weight: 10,
    cooldownTurns: 12,
    tags: ["congress", "justice"],
  },
  {
    slug: "palace_secrecy",
    type: "common",
    speaker: "nina-vale",
    category: "media",
    text: "A imprensa exige as agendas de ministros após reuniões não registradas com empresários.",
    leftChoice: {
      label: "Publicar agendas",
      effects: fx(4, -3, -2, 6),
      setFlags: [{ key: "transparent_agendas" }],
      resultText: "As agendas vêm a público, e alguns empresários cancelam novas reuniões.",
      headline: "Palácio publica agendas de ministros com empresários após pressão da imprensa",
      reaction:
        "Vamos ler cada linha dessas agendas. Transparência só vale se ninguém tiver apagado nada antes.",
    },
    rightChoice: {
      label: "Manter sigilo",
      effects: fx(-5, 3, 3, -6),
      setFlags: [{ key: "palace_secrecy_kept" }],
      resultText: "O sigilo é mantido, e o Correio Cívico promete continuar investigando.",
      headline: "Governo mantém sigilo sobre reuniões de ministros com empresários",
      reaction:
        "O sigilo não encerra a pauta, Presidente. Só nos obriga a procurar os documentos por outros caminhos.",
    },
    weight: 8,
    cooldownTurns: 16,
    uniquePerGame: true,
    tags: ["media", "scandal"],
  },
  {
    slug: "security_march",
    type: "common",
    speaker: "otavio-leme",
    category: "security",
    text: "Após uma onda de violência, manifestantes pedem patrulhamento militar temporário nas grandes cidades.",
    leftChoice: {
      label: "Autorizar patrulhas",
      effects: fx(4, 1, 2, -7),
      setFlags: [{ key: "military_patrols", expiresAfterTurns: 8 }],
      resultText:
        "Blindados ocupam as avenidas, e juristas contestam a medida no Supremo Tribunal Federal.",
      headline: "Forças Armadas iniciam patrulhas temporárias nas grandes cidades",
      reaction:
        "Ordem recebida. As tropas estarão nas avenidas ao amanhecer. A contestação jurídica é assunto seu.",
    },
    rightChoice: {
      label: "Reforçar polícia civil",
      effects: fx(-2, -3, -1, 6),
      resultText: "A polícia civil recebe reforços, mas os resultados demoram a aparecer.",
      headline: "Governo descarta tropas nas ruas e destina verba extraordinária à polícia civil",
      reaction:
        "Registro a decisão, Presidente. Se as ruas piorarem, a conta não será das Forças Armadas.",
    },
    weight: 9,
    cooldownTurns: 12,
    tags: ["security", "civil_rights"],
  },
  {
    slug: "forest_mining",
    type: "common",
    speaker: "yuri-salcedo",
    category: "environment",
    text: "Uma reserva mineral promete empregos no Norte, mas parte dela está sob proteção ambiental.",
    leftChoice: {
      label: "Liberar exploração",
      effects: fx(2, 8, 4, -6),
      setFlags: [{ key: "forest_mining_allowed" }],
      resultText: "As mineradoras chegam ao Norte, e ambientalistas anunciam protestos.",
      headline:
        "Governo libera mineração em reserva protegida do Norte e ambientalistas convocam atos",
      reaction:
        "Hoje o Norte foi ouvido! Os empregos chegam, e eu garanto que o povo daqui não esquecerá este dia.",
    },
    rightChoice: {
      label: "Preservar reserva",
      effects: fx(3, -7, -3, 5),
      setFlags: [{ key: "forest_preserved" }],
      resultText: "A reserva permanece intocada, e o governador acusa o Palácio de travar o Norte.",
      headline: "Reserva do Norte segue protegida e projeto de mineração é arquivado",
      reaction:
        "O Palácio escolheu a floresta e esqueceu quem vive ao redor dela. Vou levar essa conta a cada palanque.",
    },
    weight: 8,
    cooldownTurns: 18,
    uniquePerGame: true,
    tags: ["environment", "economy", "federalism"],
  },
  {
    slug: "inheritance_tax",
    type: "common",
    speaker: "livia-nogueira",
    category: "economy",
    text: "A equipe social propõe elevar o imposto sobre grandes heranças para financiar creches nacionais.",
    leftChoice: {
      label: "Enviar o projeto",
      effects: fx(7, -7, -3, 1),
      setFlags: [{ key: "inheritance_tax_bill" }],
      resultText: "O projeto chega à Câmara, e grandes fortunas começam a deixar o país.",
      headline: "Projeto que taxa grandes heranças para financiar creches chega à Câmara",
      reaction:
        "O projeto está protocolado. Minha equipe vai calibrar as alíquotas antes que o mercado precifique a fuga de capitais.",
    },
    rightChoice: {
      label: "Arquivar proposta",
      effects: fx(-5, 6, 3, -1),
      resultText: "A proposta é arquivada, e movimentos sociais acusam o governo de recuar.",
      headline:
        "Governo arquiva taxação de grandes heranças e plano nacional de creches fica sem verba",
      reaction:
        "Arquivar acalma os investidores, mas as creches continuam sem fonte de receita no orçamento do ano que vem.",
    },
    weight: 9,
    cooldownTurns: 14,
    tags: ["economy", "congress"],
  },
  {
    slug: "interest_rate_pressure",
    type: "common",
    speaker: "livia-nogueira",
    category: "economy",
    text: "O Banco Central elevou os juros. Seus aliados pedem que o governo pressione publicamente pela reversão.",
    leftChoice: {
      label: "Criticar o Banco",
      effects: fx(5, -5, 3, -7),
      setFlags: [{ key: "central_bank_pressured" }],
      resultText:
        "A crítica agrada aliados, mas investidores passam a duvidar da autonomia do Banco.",
      headline: "Presidente critica publicamente o Banco Central e cobra reversão da alta de juros",
      reaction:
        "Com todo o respeito, Presidente, cada frase contra o Banco custa pontos nos títulos do Tesouro amanhã cedo.",
    },
    rightChoice: {
      label: "Respeitar autonomia",
      effects: fx(-3, 6, -2, 7),
      resultText: "O Banco mantém os juros, e sua base reclama da falta de firmeza.",
      headline: "Governo respeita autonomia do Banco Central e juros altos são mantidos",
      reaction:
        "Decisão correta. A confiança do mercado se constrói assim, mesmo quando a base não aplaude.",
    },
    weight: 9,
    cooldownTurns: 12,
    tags: ["economy", "institutions"],
  },
  {
    slug: "minimum_wage",
    type: "common",
    speaker: "joana-reis",
    category: "labor",
    text: "A Central pede aumento real do salário mínimo. Pequenas empresas alertam que demissões podem seguir.",
    leftChoice: {
      label: "Aprovar aumento",
      effects: fx(8, -6, 2, 0),
      resultText: "O aumento é celebrado nas fábricas, e pequenos comércios revisam contratações.",
      headline: "Salário mínimo tem aumento real e pequenas empresas revisam contratações",
      reaction:
        "É uma vitória de quem sustenta este país com as próprias mãos. A Central vai cobrar que o aumento chegue a todos.",
    },
    rightChoice: {
      label: "Corrigir só a inflação",
      effects: fx(-6, 6, -1, 0),
      resultText: "Os empresários aprovam a cautela, e a Central convoca assembleias.",
      headline: "Salário mínimo recebe apenas correção da inflação e Central convoca assembleias",
      reaction:
        "Correção não é aumento, Presidente. Os trabalhadores vão responder nas fábricas, e não será em silêncio.",
    },
    weight: 10,
    cooldownTurns: 10,
    tags: ["labor", "economy"],
  },
  {
    slug: "flood_infrastructure",
    type: "common",
    speaker: "yuri-salcedo",
    category: "infrastructure",
    text: "Governadores pedem liberação imediata de verbas contra enchentes, sem o processo completo de licitação.",
    leftChoice: {
      label: "Liberar em emergência",
      effects: fx(6, -2, 4, -7),
      setFlags: [{ key: "emergency_procurement" }],
      resultText: "As obras começam antes das chuvas, e auditores pedem cópias dos contratos.",
      headline:
        "Verba contra enchentes é liberada sem licitação completa e obras começam antes das chuvas",
      reaction:
        "É assim que se governa para quem está com água na porta. As máquinas começam a trabalhar amanhã cedo.",
    },
    rightChoice: {
      label: "Exigir licitação",
      effects: fx(-4, -1, -3, 7),
      resultText: "A licitação segue o rito, enquanto as primeiras enchentes atingem o litoral.",
      headline:
        "Governo exige licitação completa e obras contra enchentes ficam para depois das chuvas",
      reaction:
        "Os papéis estarão impecáveis quando a água baixar. Vou lembrar disso a cada família desalojada.",
    },
    weight: 10,
    cooldownTurns: 10,
    tags: ["infrastructure", "institutions"],
  },
  {
    slug: "national_data_registry",
    type: "common",
    speaker: "tomas-azevedo",
    category: "civil_rights",
    text: "Um cadastro nacional unificado reduziria fraudes, mas concentraria dados sensíveis de toda a população.",
    leftChoice: {
      label: "Criar cadastro",
      effects: fx(2, 5, 3, -8),
      setFlags: [{ key: "national_data_registry" }],
      resultText: "O cadastro entra em operação, e juristas alertam para o risco de vazamentos.",
      headline:
        "Cadastro nacional unificado entra em operação com dados sensíveis de toda a população",
      reaction:
        "O Tribunal registra a decisão e examinará, com a devida atenção, os limites de acesso a esses dados.",
    },
    rightChoice: {
      label: "Manter bases separadas",
      effects: fx(-2, -4, -1, 7),
      resultText: "As bases seguem separadas, e as fraudes continuam a desafiar os auditores.",
      headline: "Governo desiste do cadastro único e mantém bases de dados separadas por órgão",
      reaction:
        "A cautela preserva garantias fundamentais. Caberá aos órgãos de controle combater as fraudes pelos meios existentes.",
    },
    weight: 7,
    cooldownTurns: 20,
    uniquePerGame: true,
    tags: ["civil_rights", "institutions"],
  },
  {
    slug: "import_tariffs",
    type: "common",
    speaker: "tomas-gade",
    category: "economy",
    text: "A indústria pede tarifas contra produtos estrangeiros. Consumidores temem preços mais altos.",
    leftChoice: {
      label: "Elevar tarifas",
      effects: fx(2, 5, 4, -1),
      setFlags: [{ key: "protectionist_tariffs" }],
      resultText: "A indústria comemora a proteção, e os preços sobem nas prateleiras.",
      headline: "Governo eleva tarifas sobre produtos importados e preços sobem nas prateleiras",
      reaction:
        "A indústria nacional agradece a proteção. Em troca, peço apenas que as regras não mudem no ano que vem.",
    },
    rightChoice: {
      label: "Manter abertura",
      effects: fx(-4, 4, -2, 1),
      resultText: "O comércio segue aberto, e fábricas do interior anunciam demissões.",
      headline: "Tarifas de importação permanecem baixas e fábricas do interior anunciam demissões",
      reaction:
        "Respeito a coerência, Presidente, mas voltarei a esta sala com a lista das fábricas que fecharem.",
    },
    weight: 9,
    cooldownTurns: 12,
    tags: ["economy", "foreign_affairs"],
  },
  {
    slug: "border_refugees",
    type: "common",
    speaker: "amira-sol",
    category: "foreign_affairs",
    text: "Uma crise no país vizinho leva milhares de refugiados à fronteira. Os estados pedem uma decisão imediata.",
    leftChoice: {
      label: "Abrir acolhimento",
      effects: fx(3, -4, -4, 6),
      setFlags: [{ key: "refugees_welcomed" }],
      resultText: "Abrigos são montados na fronteira, e os estados cobram recursos federais.",
      headline: "Brasil abre a fronteira a refugiados e estados cobram recursos para os abrigos",
      reaction:
        "Nossos parceiros reconhecerão este gesto. Agora devo pedir a eles que ajudem a dividir o custo do acolhimento.",
    },
    rightChoice: {
      label: "Restringir entrada",
      effects: fx(1, 3, 5, -6),
      setFlags: [{ key: "border_restricted" }],
      resultText: "A fronteira é fechada, e organismos internacionais criticam o país.",
      headline:
        "Governo fecha a fronteira a refugiados e organismos internacionais condenam o país",
      reaction:
        "Farei o possível para explicar a decisão às chancelarias, Presidente, mas nossa reputação não sairá intacta.",
    },
    weight: 7,
    cooldownTurns: 18,
    uniquePerGame: true,
    tags: ["foreign_affairs", "civil_rights"],
  },
  {
    slug: "rural_debt_relief",
    type: "common",
    speaker: "raul-mendonca",
    category: "congress",
    text: "A bancada rural condiciona votos ao perdão parcial das dívidas de produtores atingidos pela seca.",
    leftChoice: {
      label: "Conceder perdão",
      effects: fx(3, -4, 8, -3),
      resultText: "A bancada rural garante os votos, e a Fazenda recalcula o rombo.",
      headline: "Governo perdoa parte das dívidas de produtores atingidos pela seca",
      reaction:
        "A bancada rural não esquece um favor, Presidente. Pode contar com esses votos quando mais precisar deles.",
    },
    rightChoice: {
      label: "Oferecer só crédito",
      effects: fx(-2, 4, -6, 2),
      resultText: "O crédito é liberado, e a bancada rural ameaça romper com o governo.",
      headline: "Produtores atingidos pela seca recebem só crédito e bancada rural ameaça romper",
      reaction:
        "Crédito é uma ótima ideia para quem ainda tem colheita. Vou tentar acalmar a bancada, mas não prometo nada.",
    },
    weight: 9,
    cooldownTurns: 12,
    tags: ["congress", "economy"],
  },
  {
    slug: "police_body_cameras",
    type: "common",
    speaker: "joana-reis",
    category: "security",
    text: "Organizações civis pedem câmeras corporais obrigatórias. Comandos policiais ameaçam reduzir operações.",
    leftChoice: {
      label: "Tornar obrigatórias",
      effects: fx(5, -1, -3, 7),
      setFlags: [{ key: "body_cameras_required" }],
      resultText: "As câmeras chegam às fardas, e comandos policiais reduzem as patrulhas.",
      headline:
        "Câmeras corporais passam a ser obrigatórias e comandos policiais reduzem patrulhas",
      reaction:
        "Quem trabalha na periferia sabe o valor dessa decisão. Agora ninguém poderá dizer que não viu.",
    },
    rightChoice: {
      label: "Programa voluntário",
      effects: fx(-4, 1, 4, -4),
      resultText: "O programa começa sem adesão, e organizações civis protestam.",
      headline: "Câmeras corporais ficam opcionais e poucas corporações aderem ao programa",
      reaction:
        "Programa voluntário é programa no papel. A Central vai marchar com as famílias que esperavam essas câmeras.",
    },
    weight: 8,
    cooldownTurns: 16,
    uniquePerGame: true,
    tags: ["security", "civil_rights"],
  },
  {
    slug: "unfinished_bridge",
    type: "common",
    speaker: "helena-vasque",
    category: "infrastructure",
    text: "A maior obra do governo está atrasada. Trocar a empreiteira encarece o projeto; mantê-la preserva o prazo político.",
    leftChoice: {
      label: "Trocar empreiteira",
      effects: fx(2, -5, -3, 6),
      resultText: "Uma nova empreiteira assume a ponte, e a inauguração fica para o próximo ano.",
      headline: "Governo troca a empreiteira da ponte e adia a inauguração para o próximo ano",
      reaction:
        "Perdemos a data da inauguração, mas não a obra. Vou preparar a explicação antes que a oposição prepare a dela.",
    },
    rightChoice: {
      label: "Manter contrato",
      effects: fx(-4, 5, 3, -5),
      setFlags: [{ key: "questioned_contractor" }],
      resultText: "A obra segue no prazo, e o contrato vira pauta de investigação na imprensa.",
      headline: "Empreiteira questionada é mantida e obra da ponte segue no prazo previsto",
      reaction:
        "A ponte fica pronta a tempo. Só peço que ninguém do governo assine nada com essa empresa sem me consultar.",
    },
    weight: 9,
    cooldownTurns: 14,
    tags: ["infrastructure", "scandal"],
  },
  {
    slug: "presidential_broadcast",
    type: "common",
    speaker: "helena-vasque",
    category: "media",
    text: "Sua equipe propõe transmissões semanais sem entrevistas para falar diretamente com a população.",
    leftChoice: {
      label: "Falar toda semana",
      effects: fx(7, -1, -3, -6),
      setFlags: [{ key: "direct_broadcasts" }],
      resultText: "A primeira transmissão bate recordes de audiência e irrita os jornalistas.",
      headline: "Presidente estreia transmissões semanais sem entrevistas e jornalistas protestam",
      reaction:
        "A audiência foi excelente. A imprensa vai tratar cada transmissão como fuga, então cada palavra precisa ser exata.",
    },
    rightChoice: {
      label: "Manter coletivas",
      effects: fx(-2, 0, 2, 5),
      resultText: "As coletivas continuam, e perguntas incômodas voltam às manchetes.",
      headline:
        "Presidente mantém coletivas abertas e perguntas sobre o governo voltam às manchetes",
      reaction:
        "Mais trabalhoso, porém mais seguro. Vou preparar respostas para as perguntas que ninguém quer ouvir.",
    },
    weight: 8,
    cooldownTurns: 16,
    tags: ["media", "institutions"],
  },
  {
    slug: "tax_reform",
    type: "common",
    speaker: "caio-ferraz",
    category: "economy",
    text: "Um novo imposto unificado simplifica o sistema, mas retira benefícios de setores e estados influentes.",
    leftChoice: {
      label: "Unificar impostos",
      effects: fx(2, 8, -7, 5),
      setFlags: [{ key: "tax_reform_approved" }],
      schedule: [{ cardSlug: "tax_reform_backlash", delayTurns: 5 }],
      resultText: "O imposto unificado é aprovado, e os estados começam a contar as perdas.",
      headline: "Congresso aprova imposto unificado e estados perdem benefícios fiscais",
      reaction:
        "Uma reforma que esperamos por décadas. Os governadores vão cobrar a transição, e é bom estarmos preparados.",
    },
    rightChoice: {
      label: "Preservar o sistema",
      effects: fx(-2, -5, 6, -2),
      resultText: "O sistema antigo sobrevive, e os investidores voltam a reclamar da burocracia.",
      headline:
        "Governo abandona a reforma tributária e benefícios fiscais dos estados são mantidos",
      reaction:
        "Perdemos a chance de simplificar o país. Os investidores vão ler essa decisão como falta de coragem.",
    },
    conditions: { minTurn: 8 },
    weight: 6,
    cooldownTurns: 30,
    uniquePerGame: true,
    tags: ["economy", "congress", "federalism"],
  },

  // §18.2 Conditional and chained cards
  {
    slug: "strike_escalation",
    type: "chained",
    speaker: "mara-vilar",
    category: "education",
    text: "A greve fechou quase todas as escolas. Prefeitos exigem mediação; a Fazenda insiste em não ceder.",
    leftChoice: {
      label: "Reabrir negociação",
      effects: fx(6, -5, 2, 1),
      removeFlags: ["teachers_strike_active"],
      resultText: "A mediação reabre as escolas, e a Fazenda cobra o custo do acordo.",
      headline: "Mediação federal encerra greve dos professores e escolas reabrem nos estados",
      reaction:
        "Os alunos voltam amanhã, e é isso que importa. O acordo custa caro, mas custaria mais um semestre perdido.",
    },
    rightChoice: {
      label: "Cortar os dias parados",
      effects: fx(-9, 4, 4, -5),
      setFlags: [{ key: "strike_repressed" }],
      resultText: "Os salários são cortados, e a greve se transforma em protestos nas ruas.",
      headline: "Governo corta salários de professores em greve e protestos tomam as ruas",
      reaction:
        "Eu não vou defender esse corte em nenhuma escola. Cada professor punido hoje será um adversário amanhã.",
    },
    conditions: { allFlags: ["teachers_strike_active"] },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["education", "labor"],
  },
  {
    slug: "contract_investigation",
    type: "conditional",
    speaker: "tomas-azevedo",
    category: "scandal",
    text: "Auditores encontraram pagamentos incomuns. Suspender contratos interrompe obras; mantê-los preserva entregas.",
    leftChoice: {
      label: "Suspender e investigar",
      effects: fx(3, -5, -4, 9),
      setFlags: [{ key: "constitutional_precedent" }],
      resultText: "Os contratos são suspensos, e o Supremo Tribunal Federal firma um precedente.",
      headline: "Contratos sob suspeita são suspensos e Supremo Tribunal Federal firma precedente",
      reaction:
        "O Tribunal registra a colaboração do Executivo. O precedente valerá para este e para os próximos governos.",
    },
    rightChoice: {
      label: "Manter as obras",
      effects: fx(-6, 5, 4, -8),
      setFlags: [{ key: "audit_ignored" }],
      resultText: "As obras seguem, e os auditores levam o caso aos jornais.",
      headline:
        "Governo mantém obras sob suspeita e auditores levam pagamentos irregulares à imprensa",
      reaction:
        "O Tribunal não se pronuncia sobre obras. Pronuncia-se sobre provas, e elas continuarão sendo examinadas.",
    },
    conditions: { anyFlags: ["questioned_contractor", "emergency_procurement"] },
    weight: 14,
    cooldownTurns: 30,
    uniquePerGame: true,
    tags: ["scandal", "justice"],
  },
  {
    slug: "tax_reform_backlash",
    type: "chained",
    speaker: "yuri-salcedo",
    category: "federalism",
    text: "Estados perderam receita durante a transição tributária. Elas pedem compensação federal por dois anos.",
    leftChoice: {
      label: "Criar compensação",
      effects: fx(4, -5, 7, 1),
      setFlags: [{ key: "transition_fund" }],
      resultText: "O fundo acalma os governadores, e a dívida federal volta a crescer.",
      headline: "Governo cria fundo de compensação para estados que perderam receita com a reforma",
      reaction:
        "Isso é respeito com os estados! Pode dizer à Fazenda que o Norte sabe reconhecer um compromisso cumprido.",
    },
    rightChoice: {
      label: "Cobrar adaptação",
      effects: fx(-5, 5, -7, 2),
      resultText: "Os estados cortam serviços, e governadores ameaçam obstruir o Congresso.",
      headline: "Estados ficam sem compensação federal e governadores ameaçam obstruir o Congresso",
      reaction:
        "Adaptação é palavra fácil de dizer no Palácio. No Norte, ela significa escola fechada e posto sem médico.",
    },
    conditions: { allFlags: ["tax_reform_approved"] },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["federalism", "budget"],
  },
  {
    slug: "leaked_dossier",
    type: "conditional",
    speaker: "nina-vale",
    category: "scandal",
    text: "Documentos vazados ligam seu gabinete a decisões reservadas. O país espera uma resposta até o fim do dia.",
    leftChoice: {
      label: "Demitir envolvidos",
      effects: fx(5, -3, -6, 8),
      removeFlags: ["palace_secrecy_kept", "agencies_shared", "audit_ignored"],
      resultText: "Os envolvidos deixam o gabinete, e a coalizão perde aliados importantes.",
      headline:
        "Presidente demite assessores citados em documentos vazados e coalizão perde aliados",
      reaction:
        "As demissões respondem a uma parte das perguntas. O Correio Cívico continuará publicando o restante.",
    },
    rightChoice: {
      label: "Atacar o vazamento",
      effects: fx(-8, 2, 5, -8),
      setFlags: [{ key: "press_intimidated" }],
      resultText: "O Palácio ataca o vazamento, e jornalistas denunciam intimidação.",
      headline: "Palácio abre ofensiva contra vazamento e jornalistas denunciam intimidação",
      reaction:
        "Atacar quem publica não torna os documentos falsos. Amanhã a capa será sobre o que o Palácio quis esconder.",
    },
    conditions: {
      anyFlags: ["palace_secrecy_kept", "agencies_shared", "audit_ignored"],
      minTurn: 6,
    },
    weight: 13,
    cooldownTurns: 30,
    uniquePerGame: true,
    tags: ["scandal", "media"],
  },
  {
    slug: "drought_crisis",
    type: "conditional",
    speaker: "icaro-nunes",
    category: "environment",
    text: "A seca ameaça energia e abastecimento. Racionar agora reduz o risco futuro, mas atinge famílias e fábricas.",
    leftChoice: {
      label: "Iniciar racionamento",
      effects: fx(-5, -5, 1, 7),
      setFlags: [{ key: "rationing", expiresAfterTurns: 6 }],
      resultText: "O racionamento começa, e famílias e fábricas ajustam suas rotinas.",
      headline: "Governo decreta racionamento de água e energia para enfrentar a seca",
      reaction:
        "Vamos proteger primeiro os hospitais. É uma medida dura, mas evita que a seca vire emergência sanitária.",
    },
    rightChoice: {
      label: "Adiar restrições",
      effects: fx(4, 4, 1, -6),
      setFlags: [{ key: "reservoir_risk" }],
      schedule: [{ cardSlug: "blackout", delayTurns: 4 }],
      resultText: "A vida segue normal por enquanto, e os reservatórios continuam baixando.",
      headline: "Governo adia racionamento e reservatórios seguem em queda durante a seca",
      reaction:
        "Entendo o cálculo político, Presidente, mas reservatório não negocia. Meus hospitais precisam de geradores já.",
    },
    conditions: { minTurn: 12, meters: { institutions: { min: 10, max: 90 } } },
    weight: 6,
    cooldownTurns: 30,
    uniquePerGame: true,
    tags: ["environment", "infrastructure"],
  },
  {
    slug: "blackout",
    type: "chained",
    speaker: "helena-vasque",
    category: "infrastructure",
    text: "Apagões atingem três estados. É possível intervir nas distribuidoras ou subsidiar geradores privados.",
    leftChoice: {
      label: "Intervir nas empresas",
      effects: fx(2, -9, -2, 5),
      setFlags: [{ key: "energy_intervention" }],
      resultText: "O governo assume as distribuidoras, e investidores retiram capital do setor.",
      headline: "Governo intervém nas distribuidoras de energia após apagões em três estados",
      reaction:
        "Agora a luz é responsabilidade nossa, integralmente. Vou montar hoje uma equipe para cada distribuidora.",
    },
    rightChoice: {
      label: "Subsidiar geradores",
      effects: fx(-3, 7, 4, -4),
      resultText: "Geradores privados religam as cidades, e a conta chega ao orçamento.",
      headline: "Subsídio a geradores privados religa cidades atingidas por apagões",
      reaction:
        "Resolvemos a noite de hoje. A conta dos subsídios vai chegar, e alguém precisa decidir quem vai pagá-la.",
    },
    conditions: { allFlags: ["reservoir_risk"] },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["infrastructure", "economy"],
  },
  {
    slug: "green_treaty",
    type: "conditional",
    speaker: "amira-sol",
    category: "foreign_affairs",
    text: "Países vizinhos propõem metas ambientais comuns. O tratado abre crédito externo, mas limita novos projetos minerais.",
    leftChoice: {
      label: "Assinar tratado",
      effects: fx(4, -4, -3, 7),
      setFlags: [{ key: "international_green_treaty" }],
      resultText: "O tratado é assinado, e o crédito externo chega com novas exigências.",
      headline: "Brasil assina tratado ambiental regional e limita novos projetos de mineração",
      reaction:
        "Um dia importante para nossa diplomacia. Os vizinhos passam a nos ver como parceiros, não como problema.",
    },
    rightChoice: {
      label: "Recusar limites",
      effects: fx(-3, 7, 4, -6),
      resultText: "O país recusa as metas, e os vizinhos adiam acordos comerciais.",
      headline: "Brasil recusa metas ambientais comuns e vizinhos adiam acordos comerciais",
      reaction:
        "Transmitirei a posição com toda a cortesia possível, mas as portas que hoje se fecham demoram a reabrir.",
    },
    conditions: { minTurn: 18 },
    weight: 5,
    cooldownTurns: 30,
    uniquePerGame: true,
    tags: ["foreign_affairs", "environment"],
  },

  // §18.3 Critical-state cards (pillar in 1–18 or 82–99)
  {
    slug: "reconciliation_cabinet",
    type: "crisis",
    speaker: "helena-vasque",
    category: "congress",
    text: "O gabinete propõe uma reforma ministerial para reduzir a tensão com o Congresso, mas todos cobrarão espaço.",
    leftChoice: {
      label: "Dividir o gabinete",
      effects: { people: -2, market: 0, institutions: -3 },
      conditionalEffects: [{ type: "toward_center", meter: "congress", amount: 10 }],
      resultText: "Novos ministros tomam posse, e cada partido cobra sua parte do orçamento.",
      headline:
        "Reforma ministerial entrega pastas aos partidos para reduzir tensão com o Congresso",
      reaction:
        "Ganhamos tempo no Congresso. Em troca, terei ministros novos disputando a mesma fatia do orçamento.",
    },
    rightChoice: {
      label: "Governar sem reforma",
      effects: { people: 2, market: 1, institutions: 3 },
      conditionalEffects: [{ type: "away_from_center", meter: "congress", amount: 4 }],
      resultText: "O gabinete permanece intacto, e a relação com o Congresso continua tensa.",
      headline: "Presidente descarta reforma ministerial e crise com o Congresso se prolonga",
      reaction:
        "O gabinete continua coeso, e isso tem valor. Mas cada votação agora será negociada como se fosse a última.",
    },
    conditions: { anyMeters: CRITICAL("congress") },
    weight: 12,
    cooldownTurns: 30,
    uniquePerGame: true,
    tags: ["congress"],
  },
  {
    slug: "stability_pact",
    type: "crisis",
    speaker: "caio-ferraz",
    category: "economy",
    text: "Fazenda, sindicatos e empresas aceitam um pacto temporário. Para funcionar, você deve congelar parte da própria agenda.",
    leftChoice: {
      label: "Assinar o pacto",
      effects: { people: -3, congress: 2, institutions: 3 },
      conditionalEffects: [{ type: "toward_center", meter: "market", amount: 10 }],
      resultText: "O pacto é assinado, e sua agenda fica congelada por alguns meses.",
      headline: "Governo, sindicatos e empresas firmam pacto temporário de estabilidade econômica",
      reaction:
        "Os mercados vão ler este pacto como sensatez. O preço é engavetar parte da agenda por alguns meses.",
    },
    rightChoice: {
      label: "Manter liberdade",
      effects: { people: 3, congress: -1, institutions: -2 },
      conditionalEffects: [{ type: "away_from_center", meter: "market", amount: 4 }],
      resultText: "O governo mantém as mãos livres, e a desconfiança econômica persiste.",
      headline: "Presidente recusa pacto de estabilidade e desconfiança econômica persiste",
      reaction:
        "Liberdade de ação é ótima até a próxima reunião com credores. Espero que exista um plano, Presidente.",
    },
    conditions: { anyMeters: CRITICAL("market") },
    weight: 12,
    cooldownTurns: 30,
    uniquePerGame: true,
    tags: ["economy", "labor"],
  },
  {
    slug: "address_to_republic",
    type: "crisis",
    speaker: "helena-vasque",
    category: "media",
    text: "O país aguarda um pronunciamento. Você pode admitir erros e limitar seus poderes, ou convocar apoio contra seus adversários.",
    leftChoice: {
      label: "Admitir e limitar",
      effects: { market: -2, congress: -2 },
      conditionalEffects: [
        { type: "toward_center", meter: "people", amount: 10 },
        { type: "toward_center", meter: "institutions", amount: 8 },
      ],
      resultText: "O discurso admite erros, e o país reage com surpresa e cautela.",
      headline: "Presidente admite erros em pronunciamento e propõe limites aos próprios poderes",
      reaction:
        "Poucos governantes teriam dito isso em rede nacional. Agora precisamos cumprir cada limite anunciado.",
    },
    rightChoice: {
      label: "Convocar as ruas",
      effects: { market: -1, congress: 2 },
      conditionalEffects: [
        { type: "by_side", meter: "people", below: 8, above: 4 },
        { type: "by_side", meter: "institutions", below: -8, above: 4 },
      ],
      resultText: "As ruas se enchem de apoiadores, e adversários denunciam uma escalada.",
      headline: "Presidente convoca apoiadores às ruas e adversários denunciam escalada política",
      reaction:
        "As praças estão cheias, Presidente. Só lembre que multidões não assinam decretos nem votam orçamentos.",
    },
    conditions: { anyMeters: [...CRITICAL("people"), ...CRITICAL("institutions")] },
    weight: 12,
    cooldownTurns: 30,
    uniquePerGame: true,
    tags: ["media", "civil_rights"],
  },

  // The Brazilian constitutional chain (playbook §5). These are chained cards: they never enter the
  // weighted draw, they are scheduled — the country pack names the first one, and each choice
  // schedules the next link. `conditions.procedure` guards the stage, so a card can only be read
  // while the process actually stands there. The choices move the numbers of the procedure; the
  // outcome of every vote is counted by the engine against the thresholds of the country pack.
  {
    slug: "impeachment_grounds",
    type: "chained",
    speaker: "nina-vale",
    category: "scandal",
    text: "O Correio Cívico reuniu documentos que sustentam uma denúncia de responsabilidade. A reportagem sai no domingo, com ou sem a versão do Planalto.",
    leftChoice: {
      label: "Entregar os documentos",
      effects: fx(2, -2, -3, 6),
      setFlags: [{ key: "documents_released" }],
      procedure: { advance: true, evidence: -12, chamber: -4, institutionalCredibility: 8 },
      schedule: [{ cardSlug: "impeachment_petition", delayTurns: 1 }],
      resultText: "Os documentos chegam à redação, e a denúncia perde parte da força.",
      headline: "Planalto entrega documentos à imprensa e denúncia perde parte de sua sustentação",
      reaction:
        "Reconheço a atitude, Presidente. Publicarei o que está nos papéis, e o que está nos papéis desta vez ajuda o senhor.",
    },
    rightChoice: {
      label: "Recusar a entrega",
      effects: fx(-3, 0, 2, -6),
      setFlags: [{ key: "documents_withheld" }],
      procedure: {
        advance: true,
        evidence: 10,
        chamber: 5,
        publicPressure: 8,
        institutionalCredibility: -8,
      },
      schedule: [{ cardSlug: "impeachment_petition", delayTurns: 1 }],
      resultText: "A reportagem sai sem a versão do governo, e o silêncio vira manchete.",
      headline: "Governo se recusa a entregar documentos e silêncio do Planalto vira a manchete",
      reaction:
        "O silêncio também é uma resposta, Presidente, e é a única que poderei publicar no domingo. O país vai lê-la assim.",
    },
    conditions: { procedure: { type: "impeachment", stages: ["grounds_emerging"] } },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["scandal", "justice"],
  },
  {
    slug: "impeachment_petition",
    type: "chained",
    speaker: "andre-furtado",
    category: "congress",
    text: "A oposição protocola o pedido de impeachment na Câmara. Furtado pede que o governo não trate o rito como perseguição.",
    leftChoice: {
      label: "Reconhecer o rito",
      effects: fx(0, 2, 2, 5),
      setFlags: [{ key: "impeachment_petition_filed" }, { key: "defense_institutional" }],
      procedure: { advance: true, chamber: -5, publicPressure: -6, institutionalCredibility: 7 },
      schedule: [{ cardSlug: "impeachment_speaker_review", delayTurns: 1 }],
      resultText: "O Planalto declara que respeitará cada etapa, e a temperatura cai.",
      headline: "Presidência reconhece o rito do impeachment e promete respeitar todas as etapas",
      reaction:
        "É a resposta correta, e admito que não a esperava. O pedido segue de pé, mas ninguém poderá chamá-lo de golpe.",
    },
    rightChoice: {
      label: "Chamar de golpe",
      effects: fx(3, -4, -5, -7),
      setFlags: [{ key: "impeachment_petition_filed" }, { key: "defense_confrontational" }],
      procedure: { advance: true, chamber: 6, publicPressure: 10, institutionalCredibility: -9 },
      schedule: [{ cardSlug: "impeachment_speaker_review", delayTurns: 1 }],
      resultText: "O governo denuncia uma manobra, e o plenário responde no mesmo tom.",
      headline: "Planalto denuncia manobra golpista e plenário responde à Presidência no mesmo tom",
      reaction:
        "Golpe é o que se faz fora da Constituição, Presidente. Isto aqui é um protocolo, com número e data, dentro dela.",
    },
    conditions: { procedure: { type: "impeachment", stages: ["petition_filed"] } },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["congress", "justice"],
  },
  {
    slug: "impeachment_speaker_review",
    type: "chained",
    speaker: "celina-braga",
    category: "congress",
    text: "Cabe à Presidência da Câmara decidir se o pedido é lido. Braga informa que decidirá pelo regimento e pergunta o que o governo pretende oferecer à Casa.",
    leftChoice: {
      label: "Negociar a pauta",
      effects: fx(-4, 1, 8, -5),
      setFlags: [{ key: "chamber_deal_struck" }],
      procedure: {
        advance: true,
        chamber: -12,
        coalitionCohesion: 10,
        institutionalCredibility: -6,
      },
      schedule: [{ cardSlug: "impeachment_chamber_campaign", delayTurns: 1 }],
      resultText: "A pauta da Casa é negociada, e a leitura do pedido perde urgência.",
      headline: "Governo negocia pauta com a Câmara e leitura do pedido perde urgência no plenário",
      reaction:
        "A Casa tem pautas próprias, Presidente, e elas andaram hoje. O pedido continua na minha mesa, onde eu o deixei.",
    },
    rightChoice: {
      label: "Não oferecer nada",
      effects: fx(4, 0, -7, 6),
      procedure: { advance: true, chamber: 7, coalitionCohesion: -9, institutionalCredibility: 7 },
      schedule: [{ cardSlug: "impeachment_chamber_campaign", delayTurns: 1 }],
      resultText: "O governo recusa qualquer troca, e a Câmara acelera o rito.",
      headline: "Presidência recusa negociar cargos e Câmara acelera a tramitação do pedido",
      reaction:
        "Respeito quem não negocia, e registro que ninguém aqui deve nada ao senhor. O rito seguirá no ritmo da Casa.",
    },
    conditions: { procedure: { type: "impeachment", stages: ["speaker_review"] } },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["congress", "justice"],
  },
  {
    slug: "impeachment_chamber_campaign",
    type: "chained",
    speaker: "raul-mendonca",
    category: "congress",
    text: "A votação se aproxima e a base racha. Mendonça diz que um nome precisa ser entregue para segurar os votos indecisos.",
    leftChoice: {
      label: "Entregar o ministro",
      effects: fx(-2, 4, 7, -3),
      setFlags: [{ key: "minister_sacrificed" }],
      procedure: { advance: true, chamber: -14, evidence: -6, coalitionCohesion: 9 },
      schedule: [{ cardSlug: "impeachment_chamber_vote", delayTurns: 1 }],
      resultText: "O ministro cai antes da votação, e os indecisos voltam à base.",
      headline: "Ministro citado na denúncia deixa o cargo às vésperas da votação na Câmara",
      reaction:
        "Não é bonito, Presidente, e amanhã os votos estarão lá. Política é escolher quem se perde antes de perder tudo.",
    },
    rightChoice: {
      label: "Proteger o ministro",
      effects: fx(2, -3, -8, 4),
      setFlags: [{ key: "minister_shielded" }],
      procedure: { advance: true, chamber: 9, coalitionCohesion: -12, institutionalCredibility: 5 },
      schedule: [{ cardSlug: "impeachment_chamber_vote", delayTurns: 1 }],
      resultText: "O ministro fica, e a base avisa que não garante mais nada.",
      headline: "Presidente mantém ministro no cargo e base aliada retira garantia de votos",
      reaction:
        "Lealdade é uma virtude cara, e quem vai pagá-la é o senhor. Não posso mais prometer a conta na quinta-feira.",
    },
    conditions: { procedure: { type: "impeachment", stages: ["chamber_campaign"] } },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["congress", "scandal"],
  },
  {
    slug: "impeachment_chamber_vote",
    type: "chained",
    speaker: "celina-braga",
    category: "congress",
    text: "O painel será aberto hoje. São necessários dois terços da Câmara para autorizar o processo, e o Planalto decide como passará o dia da votação.",
    leftChoice: {
      label: "Convocar as ruas",
      effects: fx(6, -5, -6, -4),
      setFlags: [{ key: "streets_mobilized" }],
      procedure: { advance: true, chamber: 4, publicPressure: 12, institutionalCredibility: -5 },
      resultText: "As praças se enchem enquanto o painel é aberto.",
      headline: "Apoiadores ocupam as praças do país no dia da votação do pedido na Câmara",
      reaction:
        "As galerias estão cheias e o painel também. Nenhuma praça vota aqui dentro, Presidente, mas todas estão vendo.",
    },
    rightChoice: {
      label: "Esperar em silêncio",
      effects: fx(-3, 3, 3, 5),
      procedure: { advance: true, chamber: -4, publicPressure: -8, institutionalCredibility: 8 },
      resultText: "O Planalto acompanha a sessão sem um único pronunciamento.",
      headline: "Presidência acompanha votação em silêncio e evita qualquer pronunciamento público",
      reaction:
        "O senhor escolheu deixar a Casa decidir sozinha. Vou abrir o painel, e o número dirá o resto.",
    },
    conditions: { procedure: { type: "impeachment", stages: ["chamber_vote"] } },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["congress", "justice"],
  },
  {
    slug: "impeachment_senate_admissibility",
    type: "chained",
    speaker: "raul-mendonca",
    category: "congress",
    text: "Autorizado pela Câmara, o pedido chega ao Senado. Por maioria simples, a Casa decide instaurar o processo e afastar o presidente por até seis meses.",
    leftChoice: {
      label: "Negociar no Senado",
      effects: fx(-3, 2, 5, -4),
      procedure: { advance: true, senate: -9, coalitionCohesion: 7, institutionalCredibility: -5 },
      resultText: "O governo trabalha voto a voto até a hora da sessão.",
      headline: "Planalto negocia voto a voto no Senado às vésperas da decisão sobre o afastamento",
      reaction:
        "Estou contando cadeiras desde ontem, Presidente. Algumas ainda se movem, e é nelas que passei a noite.",
    },
    rightChoice: {
      label: "Apelar ao país",
      effects: fx(5, -4, -5, -2),
      procedure: { advance: true, senate: 5, publicPressure: 11, institutionalCredibility: -4 },
      resultText: "O pronunciamento mobiliza apoiadores e irrita o plenário.",
      headline: "Presidente apela ao país em rede nacional e irrita o plenário do Senado",
      reaction:
        "O senhor falou por cima de oitenta e um senadores. Eles ouviram, e amanhã respondem do jeito que sabem.",
    },
    conditions: { procedure: { type: "impeachment", stages: ["senate_admissibility"] } },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["congress", "justice"],
  },
  {
    slug: "impeachment_suspension",
    type: "chained",
    speaker: "helena-vasque",
    category: "justice",
    text: "O processo foi instaurado e o mandato está suspenso. A Casa Civil pergunta como o gabinete deve se comportar até o julgamento.",
    leftChoice: {
      label: "Manter o governo em marcha",
      effects: fx(2, 3, -2, 2),
      procedure: { advance: true, senate: -6, coalitionCohesion: 6 },
      resultText:
        "O gabinete segue despachando, e o país acompanha um governo em compasso de espera.",
      headline: "Gabinete mantém agenda durante o afastamento e evita paralisar a máquina federal",
      reaction:
        "O senhor volta a este gabinete ou não volta, mas o país precisa funcionar nos dois casos. Cuidarei disso.",
    },
    rightChoice: {
      label: "Transformar a espera em campanha",
      effects: fx(4, -6, -5, -5),
      setFlags: [{ key: "streets_mobilized" }],
      procedure: { advance: true, senate: 4, publicPressure: 13, institutionalCredibility: -7 },
      resultText: "O afastamento vira palanque, e a máquina federal perde o ritmo.",
      headline: "Afastamento vira palanque e máquina federal perde ritmo às vésperas do julgamento",
      reaction:
        "Estamos trocando governo por comício, Presidente. Entendo a razão, e ainda assim precisava dizer isso ao senhor.",
    },
    conditions: { procedure: { type: "impeachment", stages: ["suspended"] } },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["justice", "media"],
  },
  {
    slug: "impeachment_trial",
    type: "chained",
    speaker: "tomas-azevedo",
    category: "justice",
    text: "O julgamento no Senado é presidido pelo Supremo. São necessários dois terços para a condenação, e a defesa tem a palavra final.",
    leftChoice: {
      label: "Defender-se pelo rito",
      effects: fx(-1, 4, 3, 7),
      setFlags: [{ key: "defense_institutional" }],
      procedure: { advance: true, senate: -8, institutionalCredibility: 10 },
      resultText: "A defesa se atém aos autos, e o plenário ouve em silêncio.",
      headline: "Defesa do presidente se atém aos autos e plenário do Senado ouve em silêncio",
      reaction:
        "O senhor se defendeu como manda a Constituição, e isso será registrado nos anais. O voto, porém, é de cada senador.",
    },
    rightChoice: {
      label: "Acusar o tribunal",
      effects: fx(3, -6, -7, -10),
      setFlags: [{ key: "defense_confrontational" }],
      procedure: { advance: true, senate: 9, publicPressure: 8, institutionalCredibility: -12 },
      resultText: "A defesa vira acusação, e a sessão termina em tumulto.",
      headline: "Presidente acusa o tribunal durante o julgamento e sessão termina em tumulto",
      reaction:
        "O senhor acaba de julgar quem o julga, diante de oitenta e um votos. Vou apenas conduzir a votação agora.",
    },
    conditions: { procedure: { type: "impeachment", stages: ["senate_trial"] } },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["justice", "congress"],
  },
  {
    slug: "impeachment_acquittal",
    type: "chained",
    speaker: "helena-vasque",
    category: "justice",
    text: "O Senado não alcançou os votos para a condenação. O mandato está de volta, e a Casa Civil pergunta com que governo o senhor pretende terminá-lo.",
    leftChoice: {
      label: "Governar pelo centro",
      effects: fx(2, 5, 6, 5),
      setFlags: [{ key: "acquitted_of_impeachment" }],
      resultText: "O governo que volta é mais estreito e mais cuidadoso.",
      headline: "Presidente absolvido retoma o mandato e promete um governo de conciliação",
      reaction:
        "O senhor voltou a esta cadeira, e ela ficou menor. Governar o que resta do mandato já é uma vitória inteira.",
    },
    rightChoice: {
      label: "Cobrar a conta",
      effects: fx(4, -5, -8, -4),
      setFlags: [{ key: "acquitted_of_impeachment" }],
      resultText: "O governo volta cobrando nomes, e o Congresso anota cada um.",
      headline: "Presidente retoma o mandato cobrando a conta de quem votou por sua condenação",
      reaction:
        "Entendo a mágoa, Presidente, e ela custa caro. Quem votou contra o senhor continua votando o orçamento.",
    },
    conditions: { procedure: { active: false }, allFlags: ["impeachment_petition_filed"] },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["justice", "congress"],
  },
  {
    slug: "impeachment_shelved",
    type: "chained",
    speaker: "celina-braga",
    category: "congress",
    text: "O pedido foi arquivado e não subirá ao Senado. Braga avisa que o arquivamento vale para este pedido, não para os próximos.",
    leftChoice: {
      label: "Agradecer à Casa",
      effects: fx(0, 3, 6, 3),
      setFlags: [{ key: "impeachment_archived" }],
      resultText: "O Planalto agradece publicamente, e a Câmara cobra a fatura em silêncio.",
      headline: "Pedido de impeachment é arquivado e Presidência agradece publicamente à Câmara",
      reaction:
        "Aceito o agradecimento em nome da Casa. Lembre-se de que arquivar não é absolver, e a gaveta aqui nunca tranca.",
    },
    rightChoice: {
      label: "Declarar vitória",
      effects: fx(5, -3, -6, -5),
      setFlags: [{ key: "impeachment_archived" }],
      resultText: "O governo comemora em rede nacional, e a Câmara ouve calada.",
      headline: "Governo comemora arquivamento em rede nacional e Câmara assiste em silêncio",
      reaction:
        "Vitória sua, Presidente, não nossa. A Casa não gosta de ser usada como cenário duas vezes no mesmo ano.",
    },
    conditions: { procedure: { active: false }, allFlags: ["impeachment_petition_filed"] },
    weight: 0,
    cooldownTurns: 0,
    uniquePerGame: true,
    tags: ["congress", "justice"],
  },
];
