// Flag catalog. Labels are the narrative text shown in the chronicle.
// Legacy priorities and successor effects are provisional balance values (docs/game-rules.md).
export const flagCatalog = {
  teachers_raise: { label: "Os professores receberam reajuste salarial." },
  teachers_strike_active: { label: "A greve nacional dos professores está em curso." },
  strategic_port_concession: {
    label: "O Porto Real foi concedido a um consórcio por trinta anos.",
    legacy: true,
    legacyPriority: 10,
    successorEffects: { people: -1, market: 4, congress: 1, institutions: -2 },
  },
  agencies_shared: { label: "A coalizão passou a indicar as agências reguladoras." },
  transparent_agendas: { label: "As agendas ministeriais tornaram-se públicas." },
  palace_secrecy_kept: { label: "O Palácio manteve suas reuniões em sigilo." },
  military_patrols: { label: "Patrulhas militares ocupam as grandes cidades." },
  forest_mining_allowed: { label: "A exploração mineral foi liberada na reserva do Norte." },
  forest_preserved: { label: "A reserva florestal do Norte foi preservada." },
  inheritance_tax_bill: { label: "O imposto sobre grandes heranças chegou à Assembleia." },
  central_bank_pressured: { label: "O Banco de Aurória foi pressionado publicamente." },
  emergency_procurement: {
    label: "Obras contra enchentes foram contratadas sem licitação completa.",
  },
  national_data_registry: {
    label: "Aurória criou um cadastro nacional unificado de dados.",
    legacy: true,
    legacyPriority: 20,
    successorEffects: { people: 0, market: 2, congress: 1, institutions: -4 },
  },
  protectionist_tariffs: { label: "As tarifas de importação foram elevadas." },
  refugees_welcomed: { label: "Refugiados foram acolhidos na fronteira." },
  border_restricted: { label: "A entrada na fronteira foi restringida." },
  body_cameras_required: { label: "Câmeras corporais tornaram-se obrigatórias nas polícias." },
  questioned_contractor: { label: "O contrato com a empreiteira questionada foi mantido." },
  direct_broadcasts: { label: "A Presidência fala ao país em transmissões semanais." },
  tax_reform_approved: {
    label: "A reforma tributária unificou os impostos.",
    legacy: true,
    legacyPriority: 50,
    successorEffects: { people: 1, market: 4, congress: -3, institutions: 2 },
  },
  strike_repressed: { label: "Os dias parados da greve foram cortados." },
  constitutional_precedent: {
    label: "O Tribunal da Carta firmou um precedente contra contratos irregulares.",
    legacy: true,
    legacyPriority: 40,
    successorEffects: { people: 1, market: -2, congress: -2, institutions: 4 },
  },
  audit_ignored: { label: "O governo ignorou os achados da auditoria." },
  transition_fund: { label: "Um fundo compensa as províncias pela reforma tributária." },
  press_intimidated: { label: "O Palácio atacou a imprensa após o vazamento." },
  rationing: { label: "Água e energia estão sob racionamento." },
  reservoir_risk: { label: "Os reservatórios operam em nível de risco." },
  energy_intervention: { label: "O governo interveio nas distribuidoras de energia." },
  international_green_treaty: {
    label: "Aurória assinou o Tratado das Águas com os países vizinhos.",
    legacy: true,
    legacyPriority: 30,
    successorEffects: { people: 2, market: -2, congress: -1, institutions: 3 },
  },
};
