// Flag catalog. Labels are the narrative text shown in the chronicle.
// Legacy priorities and successor effects are provisional balance values (docs/game-rules.md).
export const flagCatalog = {
  teachers_raise: { label: "Os professores receberam reajuste salarial." },
  teachers_strike_active: { label: "A greve nacional dos professores está em curso." },
  strategic_port_concession: {
    label: "O maior porto do país foi concedido a um consórcio por trinta anos.",
    legacy: true,
    legacyPriority: 10,
    successorEffects: { people: -1, market: 4, congress: 1, institutions: -2 },
  },
  agencies_shared: { label: "A coalizão passou a indicar as agências reguladoras." },
  transparent_agendas: { label: "As agendas ministeriais tornaram-se públicas." },
  palace_secrecy_kept: { label: "O Palácio manteve suas reuniões em sigilo." },
  military_patrols: { label: "Patrulhas militares ocupam as grandes cidades." },
  forest_mining_allowed: { label: "A exploração mineral foi liberada na reserva do Norte." },
  forest_preserved: { label: "A reserva florestal do Norte foi preservada." },
  inheritance_tax_bill: { label: "O imposto sobre grandes heranças chegou à Câmara." },
  central_bank_pressured: { label: "O Banco Central foi pressionado publicamente." },
  emergency_procurement: {
    label: "Obras contra enchentes foram contratadas sem licitação completa.",
  },
  national_data_registry: {
    label: "O país criou um cadastro nacional unificado de dados.",
    legacy: true,
    legacyPriority: 20,
    successorEffects: { people: 0, market: 2, congress: 1, institutions: -4 },
  },
  protectionist_tariffs: { label: "As tarifas de importação foram elevadas." },
  refugees_welcomed: { label: "Refugiados foram acolhidos na fronteira." },
  border_restricted: { label: "A entrada na fronteira foi restringida." },
  body_cameras_required: { label: "Câmeras corporais tornaram-se obrigatórias nas polícias." },
  questioned_contractor: { label: "O contrato com a empreiteira questionada foi mantido." },
  direct_broadcasts: { label: "A Presidência fala ao país em transmissões semanais." },
  tax_reform_approved: {
    label: "A reforma tributária unificou os impostos.",
    legacy: true,
    legacyPriority: 50,
    successorEffects: { people: 1, market: 4, congress: -3, institutions: 2 },
  },
  strike_repressed: { label: "Os dias parados da greve foram cortados." },
  constitutional_precedent: {
    label: "O Supremo Tribunal Federal firmou um precedente contra contratos irregulares.",
    legacy: true,
    legacyPriority: 40,
    successorEffects: { people: 1, market: -2, congress: -2, institutions: 4 },
  },
  audit_ignored: { label: "O governo ignorou os achados da auditoria." },
  transition_fund: { label: "Um fundo compensa os estados pela reforma tributária." },
  press_intimidated: { label: "O Palácio atacou a imprensa após o vazamento." },
  rationing: { label: "Água e energia estão sob racionamento." },
  reservoir_risk: { label: "Os reservatórios operam em nível de risco." },
  energy_intervention: { label: "O governo interveio nas distribuidoras de energia." },
  international_green_treaty: {
    label: "O país assinou o Tratado das Águas com os países vizinhos.",
    legacy: true,
    legacyPriority: 30,
    successorEffects: { people: 2, market: -2, congress: -1, institutions: 3 },
  },

  // Set by the electoral prologue, never by a card: who the president was before taking office and
  // what the campaign promised. Cards may condition on them.
  origin_labour: { label: "A Presidência veio do movimento sindical." },
  origin_business: { label: "A Presidência veio do mundo empresarial." },
  origin_legal: { label: "A Presidência veio da carreira jurídica." },
  origin_congress: { label: "A Presidência veio de décadas no Congresso." },
  origin_governor: { label: "A Presidência governou um estado antes de chegar ao Planalto." },
  style_conciliator: { label: "A Presidência governa negociando antes de decidir." },
  style_technocrat: { label: "A Presidência decide por critérios técnicos." },
  style_confrontational: { label: "A Presidência enfrenta publicamente quem a contraria." },
  style_institutional: { label: "A Presidência trata o rito constitucional como limite." },
  broad_coalition: { label: "A eleição foi vencida por uma coligação de nove partidos." },
  programmatic_coalition: {
    label: "A coligação vencedora reuniu três partidos com programa comum.",
  },
  minimal_coalition: { label: "A campanha venceu quase sem alianças." },
  pledge_fiscal: { label: "A campanha prometeu responsabilidade fiscal." },
  pledge_social: { label: "A campanha prometeu expansão dos programas sociais." },
  pledge_security: { label: "A campanha prometeu enfrentar o crime organizado." },
  pledge_integrity: { label: "A campanha prometeu não fazer acordos com quem desvia." },
  campaign_austerity_pledge: { label: "Em rede nacional, a campanha prometeu cortar gastos." },
  campaign_spending_pledge: {
    label: "Em rede nacional, a campanha prometeu ampliar gastos sociais.",
  },
  campaign_cabinet_promised: { label: "Ministérios foram prometidos a partidos antes da eleição." },
  campaign_no_cabinet_deal: { label: "Nenhum ministério foi negociado durante a campanha." },
  campaign_dossier_used: { label: "A campanha divulgou um dossiê anônimo contra o adversário." },
  campaign_clean_hands: { label: "A campanha entregou às autoridades o dossiê que recebeu." },
  campaign_street_mandate: {
    label: "A eleição foi decidida em um comício com os movimentos sociais.",
  },
  campaign_market_trust: { label: "A reta final da campanha foi construída com investidores." },
  // A promise made on the campaign trail and not kept in office. The pledge itself is set by the
  // candidate's own platform; these are what happens when the bill for it arrives.
  pledge_fiscal_broken: { label: "A promessa de responsabilidade fiscal foi adiada no governo." },
  pledge_social_broken: { label: "A expansão social prometida na campanha foi segurada." },
  pledge_security_broken: { label: "O plano de segurança prometido não saiu do papel." },
  pledge_integrity_broken: { label: "O governo manteve um aliado citado em desvio." },
  campaign_licensing_promised: {
    label: "A campanha prometeu licenciar a estrada na floresta protegida.",
  },
  campaign_environment_pledge: {
    label: "A campanha se comprometeu a manter a fiscalização ambiental.",
  },

  // Set along the constitutional chain: what the government did while it was being judged.
  impeachment_petition_filed: { label: "A oposição protocolou um pedido de impeachment." },
  documents_released: { label: "O governo liberou os documentos pedidos pela investigação." },
  documents_withheld: { label: "O governo recusou-se a entregar os documentos pedidos." },
  minister_sacrificed: { label: "Um ministro foi entregue para conter a crise." },
  minister_shielded: { label: "O governo protegeu o ministro citado na denúncia." },
  defense_institutional: { label: "A defesa do governo foi conduzida pelo rito, sem ataques." },
  defense_confrontational: { label: "O governo atacou publicamente quem o julgava." },
  chamber_deal_struck: { label: "O Planalto negociou votos na Câmara para sobreviver ao pedido." },
  streets_mobilized: { label: "O governo convocou as ruas contra o processo." },
  acquitted_of_impeachment: {
    label: "O governo foi absolvido no Senado e voltou ao cargo.",
    legacy: true,
    legacyPriority: 60,
    successorEffects: { people: -2, market: -1, congress: -3, institutions: 2 },
  },
  impeachment_archived: {
    label: "A Câmara arquivou o pedido de impeachment.",
    legacy: true,
    legacyPriority: 45,
    successorEffects: { people: -1, market: 0, congress: -2, institutions: 1 },
  },
};
